#!/usr/bin/env pwsh
# Push automatiquement après chaque commit
try {
  git rev-parse --is-inside-work-tree *> $null
} catch {
  exit 0
}

$branch = git rev-parse --abbrev-ref HEAD
if ($branch -eq 'main') {
  git push origin main
} else {
  git push -u origin $branch
}
